steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-user-creation'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'user-creation-action'
      - '--gen2'
      - '--runtime=nodejs22'
      - '--region=asia-south2'
      - '--source=./functions/on-user-inserted'
      - '--entry-point=onUserInserted'
      - '--trigger-http'

options:
  logging: CLOUD_LOGGING_ONLY